apiVersion: gcp.platformref.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: platform-ref-gcp-cluster
spec:
  compositionSelector:
    matchLabels:
      provider: GCP
  id: platform-ref-gcp-cluster
  parameters:
    nodes:
      count: 3
      size: small
    services:
      operators:
        prometheus:
          version: "10.0.2"
    networkRef:
      id: platform-ref-gcp-network
  writeConnectionSecretToRef:
    name: cluster-conn
