apiVersion: gcp.platformref.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: {{cookiecutter.clusterRef}}
spec:
  compositionSelector:
    matchLabels:
      provider: GCP
  id: {{cookiecutter.clusterRef}}
  parameters:
    nodes:
      count: 1
      size: small
    services:
      operators:
        prometheus:
          version: "10.0.2"
    networkRef:
      id: {{cookiecutter.networkRef}}
  writeConnectionSecretToRef:
    name: cluster-conn
